### ISSUE TITLE
Crashing with relay and fallback usage

### ISSUE THREAD

**Issue by brane0690** [karlheyes/icecast-kh#393] opened 2023-02-01 07:53 UTC
v17.1 is crashing when relay and fallback file are used together. It won't usually crash immediately. It will crash usually when fallback action happens or client tries to connect while fallback file is active. If relay is set "on-demand 1" it will crash faster, but also with "on-demand 0" it will crash after some time on fallback action.
This wasn't problem on v15.
I didn't tested other versions. Systems tested: Centos 7 and Rocky 8 - same problem.

**Comment by brane0690** [comment] 2023-02-03 15:11
I've tested again.

kh15 - works!

kh17.1 - crash!
kh18 - crash!

kernel: icecast[54473]: segfault at 10 ip 00007efec3893570 sp 00007efebfa1ab78 error 6 in libpthread-2.17.so[7efec3887000+17000]

It mostly happens when client tries to listen while fallback file is looping.

I always reproduce error with this steps:
1. mountpoint A is relaying other server B.
2. Disconnect server B from source.
3. mountpoint A is now looping fallback file.
4. Client tries to connect to mountpoint A.
5. Client listens looping fallback file
6. Client disconnects and wait cca 10 seconds
7. Client tries to to connect to mountpoint A again.
8. Timeout
9. Client tries again - success.
10. Client disconnect and connect - server crash!

This happens in 70% of tries.

**Comment by karlheyes** [comment] 2023-02-03 15:40
A bit vague without detail of the error log.  I presume point 7/8 is the relay trying to reconnect and point 9 is is acquiring the fallback file?

karl

**Comment by brane0690** [comment] 2023-02-03 16:33
Since point 2 relay is trying to reconnect, all the time. I don't connect source on remote server B anymore.
Yes, at point 9 the client is listening the fallback file.

Interestingly, at point 8, version kh15 also experiences delay in response when client tries to listen, but it doesn't timeout (and doesn't crash server later). Seems like it was sleeping for a few seconds.

**Comment by karlheyes** [comment] 2023-02-05 20:28
Can you recheck with kh18.1.  I want to rule out some other issue first.  I have tried what you suggested a few times and it has not crashed on me but it could be dependant on load and setup of software/hardware.   If it still occurs, do a make debug and then run catchsegv icecast-c ....   and try again, let me know the output.

karl

**Comment by brane0690** [comment] 2023-02-06 14:19
I've tested kh18.1 - same crash
I didn't manage to use catchsegv... once Icecast crashes, /tmp file disappears.
I've also tested kh16 - doesn't crash, but it doesn't play fallback file at all.
So the last working version is kh15.

**Comment by karlheyes** [comment] 2023-02-06 14:41
can you get any sort of core dump at all?  just something to indicate where the problem faults, even running it in gdb.  It does look like catchsegv has been removed from later glibc which is annoying.  Do a make clean debug before running in gdb (gdb --arg icecast -c ...xml)   run  and on crash you can use gcore <filename>

**Comment by karlheyes** [comment] 2023-02-08 01:28
hmm,  not heard of that one before. It can be possible for the mpeg parsing to detect something like mp4, but I don't believe it would manifest in setting the stats as such. Only as, oh it's different, hmm looks like mp4 now, I won't parse and allow it to feed through unaligned.  Not a combo I've tried so I would need to see the log level 4 to see in more detail.  You may be seeing m4a but hard to say from just this.

**Comment by karlheyes** [comment] 2023-02-28 20:57
can you let me know what the state of these issues are with kh18.3

karl

**Comment by karlheyes** [comment] 2023-03-01 14:59
can you send me the error log  level 4 over the VPS restart?   I want to get a handle on what your setup is and what the conditions presenting are. metadata should still be requested on a relay restarting unless explicitly disabled in the xml.  I've tried here on restarting a master where the relay has a delay and the metadata comes through.

karl

**Comment by karlheyes** [comment] 2023-03-02 02:55
that does not tell me much. is the metadata coming in to icecast or not, does it appear on the status page? is the player reconnecting at all?  is the player being bounced to another mountpoint when the VPS source disappears.  Does the relay retry and if so when. Are there any errors/warnings in the parsing.  These are all key aspects that need to be made clear.  
What is the difference between the 2 servers you tried?  what is the long wait?

karl

**Comment by karlheyes** [comment] 2023-03-02 14:40
vps restarts?, you mean the feed for the stream ends and how are the mountpoint configured? are there any fall backs? Your error log says nothing about a stream ending or timing out or any listeners on the different streams

assuming you have your listener on /stream and /stream relays another mountpoint eg /feed on the same icecast,  whats is /feed, another relay and are there any fallbacks listed on either of these mountpoints.  If none are defined and /feed ends then any listeners on /stream should also end.  If /feed is off and reconnects after a while is that getting any metadata correctly?  Are either of these an on-demand relay?  I presume they are not a multi-host relay.   The more info I can see on the setup and what you are experiencing then the more I can nail down the issue.

karl.

**Comment by karlheyes** [comment] 2023-03-03 03:20
that looks like an ugly loop type of thing there.  You are relaying a mountpoint with a fallback to the mountpoint you are relaying to and have override settings.  I'll have to run some tests to check that path specifically but multiple mountpoints with common fallbacks were never a reliable use case and here you have a possible relay loop.  Separate isolated fallbacks
are what people should use in such cases.

**Comment by karlheyes** [comment] 2023-03-03 22:33
@gunsar the master should now have the fix for no metadata appearing.  The issue was that it was starting with a fallback to file and the full initialisation was missing.  The issue of the relay loop is still there but you should not expect that to work at all.

karl.

**Comment by karlheyes** [comment] 2023-03-04 01:33
the fallback file just has a initial scan for format detection once at the start, it does not read all of it or keep a copy in memory.  Are you still attempting the relay bouncing thing as that won't work well enough.  A separate fallback file reference on the secondary mount (which could be a symlink to the same file) will stop the reading end getting thrown back onto itself.

**Comment by karlheyes** [comment] 2023-03-04 11:37
I did an extra clear out of the relay if the relay is in a delayed retry  state, just in case people switch formats in-between so it would be possible to change between mp3 and aac without issue in those cases, the issue is purely the format changing mid-stream.

**Comment by karlheyes** [comment] 2023-03-07 20:47
kh20 out now.  Will close this for now.

**Closed by karlheyes** 2023-03-07 20:47 UTC
