### ISSUE TITLE
KH16 segfault with mount point defining a fallback-mounts

### ISSUE THREAD

**Issue by patphobos** [karlheyes/icecast-kh#374] opened 2022-12-16 18:40 UTC
Hi Karl,

Just tried KH16 today. Icecast KH16 is crashing when a mount point specifying a fallback-mount.
Crash is triggered by activity (source connecting, client connecting...). And almost happen immediately when source is always trying to connect.
After using git bisecting, it seem the bug has been introduced by [25fd9400a23beb8377b122bcc4d84e63fd925fe2].

[gdb backtrace.txt](https://github.com/karlheyes/icecast-kh/files/10248192/gdb.backtrace.txt)
[icecast.xml.txt](https://github.com/karlheyes/icecast-kh/files/10248226/icecast.xml.txt)

Test env : Ubuntu Bionic 18.04, automake 2.71 backported.

**Comment by karlheyes** [comment] 2022-12-19 01:47
I tagged a 16.1 update on github at https://github.com/karlheyes/icecast-kh/tags

Can you verify that is all working as expected.

karl.

**Comment by patphobos** [comment] 2022-12-19 08:39
Hi Karl,

just tried tagged version 16.1 and i'm also hiting the segfault.
debug backtrace attached : [bt icecast kh16.1.txt](https://github.com/karlheyes/icecast-kh/files/10257541/bt.icecast.kh16.1.txt)
configuration : [icecast.xml.txt](https://github.com/karlheyes/icecast-kh/files/10257551/icecast.xml.txt)
source client seen on the backtrace is Z/IPStream9X2, but not sure it care.

Patrice

**Comment by karlheyes** [comment] 2022-12-19 10:17
looks like some optimisations on that build but the info available looks sane. Nothing in the xml looks different to what I test with regularly.  Would indicate a cascading issue, ie something happens previously which is having a knock on effect, probably on a codepath with the lock changes.   Can you do a make clean debug and add level 4 to logging.  send me the error log.  If you can run icecast in valgrind (valgrind --out-file=out -v ....icecast -c ....)

karl

**Comment by patphobos** [comment] 2022-12-19 11:03
Hi Karl,

code base : kh16.1 tag
make clean debug : done
errorlog level : 4
valgrind command : `valgrind --log-file=out -v ./src/icecast -c /home/patrice/patrice.xml`

Icecast seem not to crash when lauched with valgrind. It's may be expected ?

access/error/valgrind/configure logs attached.

Best,

[access.log.with-valgrind.not-crashing.txt](https://github.com/karlheyes/icecast-kh/files/10258632/access.log.with-valgrind.not-crashing.txt)
[error.log.without-valgrind.txt](https://github.com/karlheyes/icecast-kh/files/10258633/error.log.without-valgrind.txt)
[error.log.with-valgrind.not-crashing.txt](https://github.com/karlheyes/icecast-kh/files/10258634/error.log.with-valgrind.not-crashing.txt)
[v
[icecast.xml.txt](https://github.com/karlheyes/icecast-kh/files/10258644/icecast.xml.txt)
algrind out.txt](https://github.com/karlheyes/icecast-kh/files/10258635/valgrind.out.txt)
[access.log.without-valgrind.txt](https://github.com/karlheyes/icecast-kh/files/10258636/access.log.without-valgrind.txt)
[config.log](https://github.com/karlheyes/icecast-kh/files/10258677/config.log)

**Comment by karlheyes** [comment] 2022-12-19 11:16
I found the issue on override, a refcounting bug leading to a free up which leads onto bad memory reference.

I've tagged 16.2

**Comment by patphobos** [comment] 2022-12-19 14:23
i dont hit the segfault anymore.
Fallback seems to work (dit not test fallback-override).
But had another issue #375 , probably also linked to lock changes. 

many thanks

**Comment by karlheyes** [comment] 2022-12-23 02:25
find the installer at karlheyes.github.io/icecast-2.4.0-kh16.2_win64_setup.exe

karl

**Comment by gunsar** [comment] 2022-12-23 03:48
> find the installer at karlheyes.github.io/icecast-2.4.0-kh16.2_win64_setup.exe
> 
> karl

thanks, I'll try it

**Comment by gunsar** [comment] 2022-12-24 23:59
Finally I tried Icecast 2.4.0-16.2 on Linux and Windows
I checked /server_version.xsl
Linux : Version Icecast 2.4.0-kh16.1
Windows : Version Icecast 2.4.0-kh16.2
Looks like @karlheyes may have forgotten to change the version name for linux, or maybe it's on purpose, because I see that the last change was just a little.
I tried the 2 versions above, it still runs normally
Thanks very much

**Comment by gunsar** [comment] 2022-12-25 06:53
@karlheyes
i tried Icecast 2.4.0-kh16.2 on centova, after 6 hours, server went down. tried with Icecast version 2.4.0-kh16.1 running smoothly

**Comment by BusterNeece** [comment] 2023-01-15 21:13
@karlheyes Just as a heads-up on this issue, it appears to still be happening in the latest master branch commit of this repo.

Basically, we're noticing that right as a listener connects to listen to a stream that has a relay configured, it triggers a full crash of Icecast. The system is stable right up until someone tries to connect, which, since we have the "always tune into the remote stream even if nobody's listening" setting turned off, suggests that the problem happens when tuning into the remote stream.

**Comment by karlheyes** [comment] 2023-01-15 21:39
I've been connecting to the relays quite a few times recently, checking for playback etc.  Do you have any log info to show this behaviour.  At least to see where it is getting up to and what settings are being employed

karl

**Comment by karlheyes** [comment] 2023-01-17 21:12
Anything more on this issue, I've tried an on-demand relay which sounds like your description and it seems to work ok but I don't know what the situation is.

**Comment by BusterNeece** [comment] 2023-01-17 22:20
@karlheyes Unfortunately no, from my end as soon as I set the log level higher (to 4) whatever error I was having vanished and now I can't reproduce it on my local installations.

**Comment by karlheyes** [comment] 2023-01-17 22:51
ok, it may of been fixed with a commit that you have subsequently updated with. I'll cut a release and if the issue surfaces then let me know.

**Closed** 2023-01-24 12:08 UTC
