### ISSUE TITLE
Icecast 2.4 kh4/kh5 do not function on iOS 11

### ISSUE THREAD

**Issue by acorkin** [karlheyes/icecast-kh#172] opened 2017-08-11 12:27 UTC
During testing with iOS 11 (currently up to Beta 5) Icecast has not worked on either iPhone or iPad devices. 

A bug report was submitted to Apple shortly after the release of Beta 1. However, 5 betas on with it still not fixed make it look likely no resolution will be offered on Apple's side at launch in September. 

Safari Technical Preview (macOS Sierra) and Safari on High Sierra Beta do not seem to be affected.

Older versions (2.3.3 KH11) and standard Icecast 2.4.1 do function correctly. 

The KH5 access log shows:

```
[2017-08-11  12:14:30] INFO source/source_read listener count on /stream now 1
185.205.172.46 - - [11/Aug/2017:12:14:30 +0000] "GET /stream HTTP/1.1" 200 51409 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" 5
185.205.172.46 - - [11/Aug/2017:12:14:30 +0000] "GET /stream HTTP/1.1" 200 415 "http://138.68.164.151:8000/" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" 0
[2017-08-11  12:14:30] INFO source/source_read listener count on /stream now 0
185.205.172.46 - - [11/Aug/2017:12:14:30 +0000] "GET /stream HTTP/1.1" 200 415 "http://138.68.164.151:8000/" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" 0
```

The device shows:
![img_3016](https://user-images.githubusercontent.com/2953860/29212610-68fd5216-7e97-11e7-8a99-a4702f03cfbf.jpeg)

Safari Inspector shows the following for KH5:

<img width="299" alt="screen shot 2017-08-11 at 13 11 06" src="https://user-images.githubusercontent.com/2953860/29212651-975a3b7e-7e97-11e7-9268-4ba2425e53b2.png">
<img width="299" alt="screen shot 2017-08-11 at 13 11 18" src="https://user-images.githubusercontent.com/2953860/29212652-99aaa21a-7e97-11e7-8e58-41a237d64b5b.png">

2.3.3 KH11 Safari inspector shows:
<img width="296" alt="screen shot 2017-08-11 at 13 23 27" src="https://user-images.githubusercontent.com/2953860/29212823-5ba7a7be-7e98-11e7-8774-715e24942687.png">

**Comment by DuncanFairley** [comment] 2017-08-13 06:31
Just curious if you have introaudio on this stream at all?

**Comment by karlheyes** [comment] 2017-08-13 23:36
can you clarify the link you are trying in the browser, specifically whether you have the .m3u extension on.  The browsers have become a bit particular in certain cases, like the partial request of 2 bytes.  If the mountpoint is /stream then does requesting /stream.m3u work or any other playlist from webroot?

karl.

**Comment by acorkin** [comment] 2017-08-14 10:43
This was a fresh install of Icecast KH5, I only edited the IP and source passwords etc in the config.
The URL used was http://138.68.164.151:8000/stream (this droplet is dead now)

We use Icecast as a relay server in production I have tried the M3U download on one of our production URLs however the URL contained in the M3U file is `http://localhost:80/....`

There is no intro file defined in our config.

**Comment by karlheyes** [comment] 2017-08-14 10:47
for the auto generated m3u, the hostname is taken from the original Host header, or the <hostname> setting if not provided.  If the m3u is the name of a file in webroot then it's just transferred as-is.

karl.

**Comment by acorkin** [comment] 2017-08-14 13:17
Reloading the config using the correct hostname, on iOS 11 the media player appears, immediately followed by the struck out play button (from original post). 
Safari inspector shows:

<img width="302" alt="screen shot 2017-08-14 at 14 16 55" src="https://user-images.githubusercontent.com/2953860/29273202-4983a942-80fb-11e7-9869-f8d627c2161e.png">

**Comment by acorkin** [comment] 2017-08-15 11:10
Just to update. iOS 11 Dev beta 6 released yesterday has the same issues as beta 5. 
iOS 10.3.3 works fine (screenshot from iOS 10.3.3)
![screen shot 2017-08-15 at 10 17 55](https://user-images.githubusercontent.com/2953860/29313576-bce267b8-81b2-11e7-93f6-993a76d23f1e.png)

**Comment by acorkin** [comment] 2017-08-22 10:34
Just a further update. No change on iOS 11 Beta 7 which was released yesterday.

**Comment by acorkin** [comment] 2017-08-31 13:31
iOS 11 Beta 8 is the same. Submitted another bug-report to Apple. I'm just concerned as it's getting close to launch

**Comment by dehy** [comment] 2017-09-20 07:47
iOS 11 is live and this is not working.

**Comment by dom-robinson** [comment] 2017-09-21 07:56
I am having users report same issues on other Icecast implementations too. Currently investigating. Have filed a bug report with Apple.

**Comment by andistuder** [comment] 2017-09-21 12:33
I have the same issues with our own network: 
https://stream-relay-geo.ntslive.net/stream

However, I noticed that Airtime.Pro endpoints work: http://nts2.out.airtime.pro:8000/nts2_a and as far as I know they use the Icecast KH branch also - with customisation?

**Comment by andistuder** [comment] 2017-09-21 13:15
I did some further testing on the issues. I can stream on IOS11 when running Icecast 2.4.1 (not KH branch). 
I wonder if related to the Security Improvements, as listed here: 
http://icecast.org/news/icecast-release-2_4_1/

**Comment by andistuder** [comment] 2017-09-21 14:30
I've just tested 2.4.0-kh1 - it seems to work well in iOS11.

**Comment by dom-robinson** [comment] 2017-09-21 14:35
Interesting well done andistuder ! 
if you have kh1 running and I have kh3 reported failing it is narrowing down.. :)
Problem for me is i am getting user feedback but don't have IOS11 here to test... Not that keen to update my own phone till the issue is isolated!

**Comment by andistuder** [comment] 2017-09-21 14:42
@dom-robinson if on Mac, consider using the Simulator app to test. You may need to upgrade XCode to get virtual devices with iOS11.

**Comment by dom-robinson** [comment] 2017-09-21 14:43
ah shoulda thunk o' that! Nice one Andi :)

—

**Comment by csernikmarton** [comment] 2017-09-21 15:56
Just adding my two cents: as several people reported, kh1 works fine, I can also confirm this. I tried all the versions above kh1: from kh2 upwards none of the versions work under iOS 11.

**Comment by karlheyes** [comment] 2017-09-21 16:34
can you confirm that the /mountpoint.m3u works?

What needs to identified is what happens in the connection side of things.  It will be some weird issue with range requests/ http1.1 or connection dropping

karl.

**Comment by dom-robinson** [comment] 2017-09-21 16:49
interesting - i can confirm that (under simulator) adding .m3u does launch the stream on Icecast 2.4.0-kh3

—

**Comment by csernikmarton** [comment] 2017-09-21 17:57
The same here, although it takes some good 7-8 seconds to start.
Here's a stream to test if needed: http://live.leanstream.co/CFXJFM.m3u

**Comment by dom-robinson** [comment] 2017-09-21 20:34
Inspector reports "Failed to load resource: Plug-in handled load" when launching without the m3u.

With the .m3u suffix it launches directly (I assume the user agent it picks for mpeg audio is discovered by virtue of the explicit m3u) however if its not there <im guessing> it just doesnt know what to use and so 'Fails to load' a suitable decoder plug in.

However its not as simple as 'just' adding .m3u since that then causes other issues in other browsers. 

As a work around I tested the following method within a web page:

`

<!doctype html>
--
  |  
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  |  
  | <title>TTNS</title>
  | <meta name="description" content="TheThursdayNightShow">
  | <meta name="author" content="TTNS">
  |  
  | <link rel="stylesheet" href="css/styles.css?v=1.0">
  |  
  | 
  | </head>
  |  
  | <body>
  | <script src="js/scripts.js"></script>
  |  
  | <audio controls autoplay>
  | <source src="http://listen.thethursdaynightshow.com/live" type="audio/mpeg">
  | <source src="http://listen.thethursdaynightshow.com/live.m3u" type="audio/mpeg" >
  | Your browser does not support the audio tag.
  | </audio>
  |  
  | </body>
  | </html>

`
This gives both browsers (IOS and desktop chrome / Safari / ffox etc) a URL that they can use. The autoplay however does not work on IOS.

It'd be nice to understand what IOS has changed but at least there is something of a workaround (so far!)

**Comment by karlheyes** [comment] 2017-09-21 21:30
can you try the master branch to see if that is any better?

karl.

**Comment by dom-robinson** [comment] 2017-09-21 21:37
Wont be tonight carl Im afraid. Ill try to spin it up if i get time tomorrow.

—

**Comment by csernikmarton** [comment] 2017-09-22 06:46
@karlheyes I‘ve just tried the master branch, it works absolutely fine: http://icecasttest.leanstream.co/IM0201-MP3

**Comment by andistuder** [comment] 2017-09-22 07:29
@karlheyes does this indicate https://github.com/karlheyes/icecast-kh/commit/ddfd9c5a09cac2cbcd41d9b72f4e89f7932960d2 addressed the issue?

**Comment by karlheyes** [comment] 2017-09-22 09:38
excellent.  indeed that was the change I did, avoiding range handling on streams.  Can you make sure of other players  For some reason my vlc was having some issue but other players were ok for me. Don't want to break others just to fix one.

karl

**Comment by csernikmarton** [comment] 2017-09-22 09:53
Playing fine for me on OS X 10.12.6 (Chrome, Firefox, Safari, Opera), iOS 11 (Safari, Chrome), Android 6 (Chrome). Let them stream for a few minutes, no problems coming up.

**Comment by csernikmarton** [comment] 2017-09-23 14:24
@karlheyes Just curious, if no issues come up for others either, when can this update be considered production-ready?

**Comment by karlheyes** [comment] 2017-09-23 15:44
I think so.  The only other commit since kh5 is for building against openssl 1.1

karl

**Comment by andrew867** [comment] 2017-09-23 19:02
@karlheyes Any estimate when the next release will be that incorporates this fix?

**Comment by karlheyes** [comment] 2017-09-23 19:24
I suppose I could get that out in the next few days.  If there are any other issues then shout now.

karl.

**Comment by rickphp** [comment] 2017-10-05 19:50
I've upgraded to the latest master build, the stream stops after 10-20 seconds on iOS 11. Is anyone else getting this?

**Comment by andrew867** [comment] 2017-10-05 20:35
@rickphp Seems to be working fine for me, you can try my stream at:
https://therev.ca/player/
or
http://158.69.227.214:8008/stream

**Comment by luca066** [comment] 2017-10-05 23:42
Sorry guys, I'm using version 2.4.0-kh6 , but I still have the iOS issue.
Does KH6 version fix the issue or do I have to use development HK branch?
Thanks

**Comment by kjwierenga** [comment] 2017-10-06 12:42
managed to reproduce the problem and I can confirm that commit https://github.com/karlheyes/icecast-kh/commit/ddfd9c5a09cac2cbcd41d9b72f4e89f7932960d2 fixes the problem

**Comment by andrew867** [comment] 2017-10-06 13:07
@rickphp @kjwierenga The fix is in master branch, it's post kh6.

**Comment by kjwierenga** [comment] 2017-10-06 13:19
👍

**Comment by rickphp** [comment] 2017-10-06 15:57
I am running the latest master branch but users are complaining of the stream stopping after 10-20 seconds. They weren't able to tune in at all before the update, they had the crossed out play button. Any ideas?

**Comment by rickphp** [comment] 2017-10-06 17:41
Do you get the same behavior with 46.28.49.164:7328/stream ?

**Comment by andistuder** [comment] 2017-10-06 18:12
@rickphp could you report which platforms/clients your users use to play the stream when they experience stability issues?

**Comment by luca066** [comment] 2017-10-07 10:27
I tested a stream on Safari, FF, Chrome, Edge, IE, Ghost: they stream the audio with no issue.
OSX and Windows 10.

**Comment by Evervision** [comment] 2017-11-15 18:19
As kh7 has been released and talks about fixing iOS 11 breaking, can I assume this issue has been fixed? Is there a reason this issue hasn't been closed yet?

**Comment by karlheyes** [comment] 2017-12-05 02:43
kh8 is out now, afaik the ios11 issue is resolved.  Any further issues then open a separate ticket.

karl.

**Closed by karlheyes** 2017-12-05 02:43 UTC

**Comment by dom-robinson** [comment] 2017-12-05 07:58
Thanks Karl all sorted: by the way did you get my emails regarding the monthly podcast i run about streaming technology/industry… hoping to have you join us in Jan...

(See your plus.com email address...)

Dom Robinson 
www.id3as.co.uk
